### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by RobinRMC** [Dr3nz4r/impostor-ipfilter#2]
When I allow my IP address to create a lobby, it still says that I'm not allowed to create a lobby.

**Comment by Dr3nz4r** [comment]
Are you hosting the server in the same local network?

If so, check the notes section in the readme:

> The IP checked against, will always resolve to your local network gateway if the server runs in the same network, If you have an idea on how to solve this, feel free to submit a PR or open an issue with some idea.

**Comment by RobinRMC** [comment]
I'm hosting the server from my own computer, but I connect externally.

**Comment by Dr3nz4r** [comment]
Connect externally as in using mobile internet or what? If the server is on the same network you need to use your gateway ip. Like 192.168.0.1 or 10.0.0.1 etc. Else you need to enter your public IP so the IP your provider gives to you like 123.213.111.222

**Comment by RobinRMC** [comment]
I've tried everything. Nothing works.

Contact me here: https://discord.gg/gV8wanMBXA (This is just a server to prevent randoms from adding me. Not an advertisement.)
